### ISSUE TITLE
Calling all Scientists, Researchers, Students! Add relevant lab related math functions!

### ISSUE THREAD

**Issue by sdhutchins** [sdhutchins/labrat#1]
I'm looking to add more useful lab related math functions to this package. Check [here](https://github.com/sdhutchins/labrat/tree/master/labrat/math) for what I currently have which is not much.

If you have any other ideas about the package, please chime in on this issue.

**Comment by sdhutchins** [comment]
Thanks @Dheeraj1998, @AndyTempel , @karillith , and @lncxd for your contributions!!!

If you have any other ideas about the package, let me know.

**Comment by peter-parque** [comment]
Hello! Could I add a function that calculates the speed of an electromagnetic wave based on the frequency/wavelength and gives an approximate position for the wave on the EM spectrum?

**Comment by sdhutchins** [comment]
@peter-parque This is geared more towards molecular and computational biology, but sure! Feel free.
